//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blood_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thana()
        {
            this.Requisition = new HashSet<Requisition>();
        }
    
        public int ID { get; set; }
        public Nullable<int> District_ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisition> Requisition { get; set; }
    }
}
